name: angular_modern_charts
description: Angular wrapper for the modern charts library. This wrapper
  utilizes core angular concepts such as, component/model/template structure and
  property bindings.
version: 0.1.2
homepage: https://github.com/dejan-marlovic/angular_modern_charts
author: Dejan Marlovic <dmarlovic83@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  angular: ^6.0.1
  json_annotation: ^4.0.0
  modern_charts: ^0.1.19
  sass_builder: ^2.1.3

dev_dependencies:
  build_runner: ^1.11.1
